### ISSUE TITLE
spc --help ...HELP on Windows!! 

### ISSUE THREAD

**Issue by MCSZ** [SciCrunch/sparc-curation#56]
```
$ spc --help
[2020-08-14 17:51:59,757] -    ERROR -     pyontutils -    namespaces.py:70   - [Errno 2] No such file or directory: 'C:\\Users\\mszeigler\\AppData\\Roaming\\Python\\Python38\\site-packages\\nifstd\\scigraph\\curie_map.yaml'
Traceback (most recent call last):
  File "C:\Users\mszeigler\AppData\Roaming\Python\Python38\site-packages\pyontutils\namespaces.py", line 64, in getCuries
    with open(curies_location, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mszeigler\\AppData\\Roaming\\Python\\Python38\\site-packages\\nifstd\\scigraph\\curie_map.yaml'
[2020-08-14 17:51:59,783] -  WARNING -       orthauth -          core.py:655  - attempting to get a default value for curies that is a list did you want get_path?
[2020-08-14 17:51:59,795] -  WARNING -       orthauth -          core.py:763  - attempting to get a default value for curies that is a list did you want get_path?
Traceback (most recent call last):
  File "C:\Users\mszeigler\AppData\Roaming\Python\Python38\site-packages\pyontutils\namespaces.py", line 64, in getCuries
    with open(curies_location, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mszeigler\\AppData\\Roaming\\Python\\Python38\\site-packages\\nifstd\\scigraph\\curie_map.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mszeigler\AppData\Roaming\Python\Python38\Scripts\spc-script.py", line 11, in <module>
    load_entry_point('sparcur', 'console_scripts', 'spc')()
  File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\mszeigler\git\sparc-curation\sparcur\cli.py", line 239, in <module>
    from pyontutils.core import OntResGit
  File "C:\Users\mszeigler\AppData\Roaming\Python\Python38\site-packages\pyontutils\core.py", line 27, in <module>
    from pyontutils import combinators as cmb
  File "C:\Users\mszeigler\AppData\Roaming\Python\Python38\site-packages\pyontutils\combinators.py", line 5, in <module>
    from pyontutils.namespaces import TEMP
  File "C:\Users\mszeigler\AppData\Roaming\Python\Python38\site-packages\pyontutils\namespaces.py", line 223, in <module>
    PREFIXES = _loadPrefixes()
  File "C:\Users\mszeigler\AppData\Roaming\Python\Python38\site-packages\pyontutils\namespaces.py", line 111, in _loadPrefixes
    curie_map = getCuries(auth.get_path('curies'))
  File "C:\Users\mszeigler\AppData\Roaming\Python\Python38\site-packages\pyontutils\namespaces.py", line 104, in getCuries
    raise TypeError(f'{curies_location} does not exist and '
TypeError: C:\Users\mszeigler\AppData\Roaming\Python\Python38\site-packages\nifstd\scigraph\curie_map.yaml does not exist and is not at the default ../nifstd/scigraph/curie_map.yaml so we will not write to it. You can update it manually if you want to keep it at that location.
```

**Comment by tgbugs** [comment]
```
test\test_units.py:3: in <module>
    from .common import *
test\common.py:6: in <module>
    debug_dict) = units.make_unit_parser(units_folder)
pysercomb\parsers\units.py:205: in make_unit_parser
    dicts = get_unit_dicts(units_path)
pysercomb\parsers\units.py:185: in get_unit_dicts
    ('si-prefixes-data.rkt',
pysercomb\parsers\units.py:184: in <listcomp>
    return [get_quoted_list(units_path, _) for _ in
pysercomb\parsers\units.py:13: in get_quoted_list
    with open((folderpath / filename).as_posix(), 'rt') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/tom/AppData/Roaming/Python/Python37/protc-lib/protc/units/si-prefixes-data.rkt'
```

**Comment by tgbugs** [comment]
Looks like these were being cause by missing data files or files that were not being found by orthauth/pysercomb. Likely related to https://github.com/tgbugs/orthauth/issues/9.
